export const theme = {
  colors: {
    primary: '#FF6B6B',
    primaryDark: '#E55555',
    primaryLight: '#FF9999',
    primarySoft: '#FFB3B3',
    primaryPale: '#FFE5E5',
    primaryBg: '#FFF5F5',
    textPrimary: '#CC4444',
    textSecondary: '#FF9999',
    background: '#FFFAFA',
    border: '#FFCCCC',
    white: '#FFFFFF',
    success: '#81C784',
    warning: '#FFB74D',
    error: '#E57373',
    disabled: '#B0BEC5',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    xxxl: 32,
  },
  borderRadius: {
    sm: 4,
    md: 8,
    lg: 12,
    xl: 16,
    full: 999,
  },
  fontSize: {
    xs: 12,
    sm: 14,
    md: 16,
    lg: 18,
    xl: 20,
    xxl: 24,
    xxxl: 28,
  },
  fontWeight: {
    light: '300' as const,
    normal: '400' as const,
    medium: '500' as const,
    semibold: '600' as const,
    bold: '700' as const,
  },
  shadow: {
    color: '#FF6B6B',
    opacity: 0.1,
    radius: 4,
    elevation: 2,
  },
};