export const theme = {
  colors: {
    primary: "#66BB6A",
    primaryDark: "#4CAF50",
    primaryLight: "#81C784",
    primarySoft: "#A5D6A7",
    primaryPale: "#C8E6C9",
    primaryBg: "#F1F8E9",
    textPrimary: "#2E7D32",
    textSecondary: "#66BB6A",
    background: "#FAFAFA",
    border: "#C8E6C9",
    white: "#FFFFFF",
    success: "#4CAF50",
    warning: "#FF9800",
    error: "#F44336",
    disabled: "#9E9E9E",
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    xxxl: 32,
  },
  borderRadius: {
    sm: 4,
    md: 8,
    lg: 12,
    xl: 16,
    full: 999,
  },
  fontSize: {
    xs: 12,
    sm: 14,
    md: 16,
    lg: 18,
    xl: 20,
    xxl: 24,
    xxxl: 28,
  },
  fontWeight: {
    light: "300" as const,
    normal: "400" as const,
    medium: "500" as const,
    semibold: "600" as const,
    bold: "700" as const,
  },
  fontFamily: {
    heading: "Poppins",
    body: "Inter",
  },
  shadow: {
    color: "#66BB6A",
    opacity: 0.1,
    radius: 4,
    elevation: 2,
  },
};
